### ISSUE TITLE
Having an Issue with the play.php file.

### ISSUE THREAD

**Issue by JustinSnyder611** [iharshraj1123/offline-youtube-browser-video-organizer#6]
I set up everything and "localhost/YouTube" looks fine and has the videos I put into it. But when I try and click on a video I don't get the normal YouTube video layout, I get a naked video player that I have to scroll down to see all of it.

Really love this project and would really appreciate some help, thanks!

![Capture](https://github.com/iharshraj1123/offline-youtube-browser-video-organizer/assets/108856780/1ba76016-9004-4d54-9284-a6bf171d8bd7)

**Comment by iharshraj1123** [comment]
Im actually surprised someone used it lol, its such a hard to setup project. I'm really thankful as well and apologize that it's not very friendly to install cuz it was meant to be a personal project.

The issue was that I had not updated the project in almost a year.

I have updated the project, delete the current Youtube folder, and replace it with the new youtube folder. Let me know if it fixes the issue.

You might have noticed that the third from the right button (the place where fullscreen button is present) doesn't work.

You can either delete that element or, if you wish you can download the [electron player](https://drive.google.com/drive/folders/18UFdW4VaAEURjlz-P35kFZAp5TgF99ky), this will activate the pop-up (pip) feature in the play.php

Although electron player is only for windows, and could be a bit unstable to install. But you can give it a try cuz this feature is definitely worth it. If it doesn't work feel free to delete that element or if you are confident dive into the source code of electron player, you will just have to squeak a bit.

**Comment by iharshraj1123** [comment]
Also you would need another step for electron app

Open your xampp, in Apache row click on config, then httpd.conf (first option)

First search for "\<IfModule alias_module>"
And add:
```
    Alias "/d:" "D:/"
    Alias "/c:" "C:/"
```
before "<\/IfModule>"

Add these codes in bottom of httpd.conf:
```
<Directory "D:/">
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Require all granted
</Directory>
<Directory "C:/">
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Require all granted
</Directory>
```

**Comment by JustinSnyder611** [comment]
I tried to fix it and I think I made it worse 😅

Do you have a discord so we can talk easier? Thanks for the help

**Comment by iharshraj1123** [comment]
harsh0551
